spring:
  datasource:
  #mysql -h 139.196.79.125 -P 3306 -u root -p991116
    url: jdbc:mysql://localhost:3306/schoolc?serverTimezone=CTT&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
    username: root
    password: ChenLi123
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
  jackson:
    time-zone: GMT+8
mybatis:
  mapper-locations: /dataImpl/*.xml